// Letter values for numerology calculations
const letterValues = {
	A: 1,
	B: 2,
	C: 3,
	D: 4,
	E: 5,
	F: 6,
	G: 7,
	H: 8,
	I: 9,
	J: 1,
	K: 2,
	L: 3,
	M: 4,
	N: 5,
	O: 6,
	P: 7,
	Q: 8,
	R: 9,
	S: 1,
	T: 2,
	U: 3,
	V: 4,
	W: 5,
	X: 6,
	Y: 7,
	Z: 8,
};

const baseVowels = ['A', 'E', 'I', 'O', 'U'];

// Vietnamese accent mapping for normalization
const vietnameseAccents = {
	à: 'a',
	á: 'a',
	ả: 'a',
	ã: 'a',
	ạ: 'a',
	ă: 'a',
	ằ: 'a',
	ắ: 'a',
	ẳ: 'a',
	ẵ: 'a',
	ặ: 'a',
	â: 'a',
	ầ: 'a',
	ấ: 'a',
	ẩ: 'a',
	ẫ: 'a',
	ậ: 'a',
	è: 'e',
	é: 'e',
	ẻ: 'e',
	ẽ: 'e',
	ẹ: 'e',
	ê: 'e',
	ề: 'e',
	ế: 'e',
	ể: 'e',
	ễ: 'e',
	ệ: 'e',
	ì: 'i',
	í: 'i',
	ỉ: 'i',
	ĩ: 'i',
	ị: 'i',
	ò: 'o',
	ó: 'o',
	ỏ: 'o',
	õ: 'o',
	ọ: 'o',
	ô: 'o',
	ồ: 'o',
	ố: 'o',
	ổ: 'o',
	ỗ: 'o',
	ộ: 'o',
	ơ: 'o',
	ờ: 'o',
	ớ: 'o',
	ở: 'o',
	ỡ: 'o',
	ợ: 'o',
	ù: 'u',
	ú: 'u',
	ủ: 'u',
	ũ: 'u',
	ụ: 'u',
	ư: 'u',
	ừ: 'u',
	ứ: 'u',
	ử: 'u',
	ữ: 'u',
	ự: 'u',
	ỳ: 'y',
	ý: 'y',
	ỷ: 'y',
	ỹ: 'y',
	ỵ: 'y',
	đ: 'd',
};

// Number descriptions for all numerology numbers
const descriptions = {
	lifePathDescriptions: {
		1: 'Con đường học tự chủ và tiên phong; dám chọn lối riêng, dẫn dắt bằng gương mẫu.',
		2: 'Con đường học hợp tác – cân bằng – kiên nhẫn.',
		3: 'Con đường học biểu đạt & lan tỏa niềm vui.',
		4: 'Con đường học kỷ luật – xây nền tảng – làm việc kiên trì.',
		5: 'Con đường học tự do – linh hoạt – thích nghi – đổi mới.',
		6: 'Con đường học trách nhiệm – yêu thương – kiến tạo tổ ấm.',
		7: 'Con đường tìm chân lý – sự thật – trí tuệ tâm linh.',
		8: 'Con đường học quản trị – quyền lực – trách nhiệm xã hội.',
		9: 'Con đường học phụng sự – nhân văn – trí tuệ.',
		11: 'Con đường học khai sáng và truyền cảm hứng bằng trực giác – lòng nhân ái.',
		22: 'Con đường học kiến tạo bền vững – hệ thống hóa tầm nhìn lớn.',
		33: 'Con đường học tình yêu phụng sự & trách nhiệm cộng đồng.',
	},
	destinyDescriptions: {
		1: 'Mục đích sống là khởi xướng giá trị mới cho tập thể/cộng đồng.',
		2: 'Sứ mệnh trở thành người kết nối, bắc cầu giữa con người.',
		3: 'Sứ mệnh trở thành người truyền cảm hứng qua biểu đạt.',
		4: 'Mục đích sống: tạo cấu trúc & hệ thống bền vững cho người khác.',
		5: 'Mục đích sống: lan tỏa tinh thần tự do & đổi mới.',
		6: 'Mục đích sống: xây nền tảng tình thương & trách nhiệm cho cộng đồng.',
		7: 'Mục đích: mang tri thức & minh triết để khai sáng cộng đồng.',
		8: 'Mục đích: xây dựng thành công & ảnh hưởng thực tế.',
		9: 'Mục đích: dùng trí tuệ & lòng nhân ái để nâng cao cộng đồng.',
		11: 'Mục đích: thắp sáng và nâng độ ý thức cộng đồng.',
		22: 'Mục đích: xây dựng công trình/hệ thống lớn cho nhân loại.',
		33: 'Mục đích: lan tỏa tình yêu, chữa lành, trở thành thầy/cô giáo tình thần.',
	},
	soulUrgeDescriptions: {
		1: 'Trong sâu thẳm, bạn khát khao được lãnh đạo và độc lập. Bạn muốn được công nhận như một người tiên phong và có ảnh hưởng. Hãy theo đuổi những mục tiêu mà bạn thực sự đam mê.',
		2: 'Trong sâu thẳm, bạn khát khao hòa bình và sự kết nối. Bạn muốn được yêu thương và tạo ra sự hài hòa xung quanh mình. Hãy tìm kiếm những mối quan hệ sâu sắc và ý nghĩa.',
		3: 'Trong sâu thẳm, bạn khát khao được thể hiện bản thân sáng tạo. Bạn muốn mang lại niềm vui và cảm hứng cho người khác. Hãy theo đuổi những hoạt động nghệ thuật và sáng tạo.',
		4: 'Trong sâu thẳm, bạn khát khao sự ổn định và an toàn. Bạn muốn xây dựng một nền tảng vững chắc cho cuộc sống. Hãy tập trung vào việc tạo ra trật tự và cấu trúc.',
		5: 'Trong sâu thẳm, bạn khát khao tự do và phiêu lưu. Bạn muốn khám phá thế giới và trải nghiệm những điều mới mẻ. Hãy cho phép bản thân được du lịch và khám phá.',
		6: 'Trong sâu thẳm, bạn khát khao được chăm sóc và nuôi dưỡng người khác. Bạn muốn tạo ra một môi trường ấm áp và yêu thương. Hãy dành thời gian cho gia đình và những người thân yêu.',
		7: 'Trong sâu thẳm, bạn khát khao hiểu biết và sự thật. Bạn muốn khám phá những bí ẩn của cuộc sống và vũ trụ. Hãy dành thời gian cho việc học hỏi và tìm hiểu tâm linh.',
		8: 'Trong sâu thẳm, bạn khát khao thành công và công nhận. Bạn muốn đạt được địa vị và ảnh hưởng trong xã hội. Hãy theo đuổi những mục tiêu kinh doanh và tài chính của mình.',
		9: 'Trong sâu thẳm, bạn khát khao cống hiến cho nhân loại. Bạn muốn tạo ra sự khác biệt tích cực trên thế giới. Hãy tham gia vào những hoạt động từ thiện và xã hội.',
		11: 'Trong sâu thẳm, bạn khát khao kết nối với điều thiêng liêng. Bạn muốn truyền cảm hứng tâm linh cho người khác. Hãy phát triển khả năng trực giác và tâm linh của mình.',
		22: 'Trong sâu thẳm, bạn khát khao tạo ra những thành tựu vĩ đại. Bạn muốn để lại dấu ấn lớn lao cho thế giới. Hãy theo đuổi những dự án có tầm ảnh hưởng rộng lớn.',
		33: 'Trong sâu thẳm, bạn khát khao yêu thương và chữa lành. Bạn muốn mang tình yêu vô điều kiện đến với mọi người. Hãy phát triển lòng từ bi và khả năng chữa lành của mình.',
	},
	personalityDescriptions: {
		1: 'Người khác nhìn bạn như một người lãnh đạo tự tin và quyết đoán. Bạn toát lên vẻ độc lập và mạnh mẽ, khiến người khác tin tưởng và muốn theo bạn. Bạn có khí chất của một người tiên phong.',
		2: 'Người khác nhìn bạn như một người hòa đồng và dễ gần. Bạn toát lên vẻ nhẹ nhàng và thân thiện, khiến mọi người cảm thấy thoải mái khi ở bên bạn. Bạn có khí chất của một người hòa giải.',
		3: 'Người khác nhìn bạn như một người vui vẻ và sáng tạo. Bạn toát lên vẻ năng động và hấp dẫn, khiến mọi người muốn ở gần bạn để cảm nhận năng lượng tích cực. Bạn có khí chất của một nghệ sĩ.',
		4: 'Người khác nhìn bạn như một người đáng tin cậy và thực tế. Bạn toát lên vẻ ổn định và có tổ chức, khiến mọi người tin tưởng vào khả năng của bạn. Bạn có khí chất của một người xây dựng.',
		5: 'Người khác nhìn bạn như một người tự do và thú vị. Bạn toát lên vẻ năng động và không thể đoán trước, khiến mọi người tò mò về những gì bạn sẽ làm tiếp theo. Bạn có khí chất của một nhà thám hiểm.',
		6: 'Người khác nhìn bạn như một người ấm áp và quan tâm. Bạn toát lên vẻ chăm sóc và bảo vệ, khiến mọi người cảm thấy an toàn và được yêu thương khi ở bên bạn. Bạn có khí chất của một người mẹ.',
		7: 'Người khác nhìn bạn như một người bí ẩn và thông thái. Bạn toát lên vẻ sâu sắc và trầm tĩnh, khiến mọi người tôn trọng và muốn tìm hiểu về bạn. Bạn có khí chất của một nhà hiền triết.',
		8: 'Người khác nhìn bạn như một người thành công và quyền lực. Bạn toát lên vẻ chuyên nghiệp và có uy quyền, khiến mọi người kính trọng và tin tưởng vào khả năng lãnh đạo của bạn. Bạn có khí chất của một CEO.',
		9: 'Người khác nhìn bạn như một người bao dung và hiểu biết. Bạn toát lên vẻ trí tuệ và lòng từ bi, khiến mọi người cảm thấy được hiểu và chấp nhận. Bạn có khí chất của một người thầy.',
		11: 'Người khác nhìn bạn như một người đặc biệt và truyền cảm hứng. Bạn toát lên vẻ tâm linh và chiều sâu, khiến mọi người cảm thấy được nâng đỡ về mặt tinh thần khi ở gần bạn.',
		22: 'Người khác nhìn bạn như một người có tầm nhìn và khả năng thực hiện lớn lao. Bạn toát lên vẻ của một người có thể tạo ra những thay đổi có ý nghĩa cho thế giới.',
		33: 'Người khác nhìn bạn như một người chữa lành và yêu thương. Bạn toát lên vẻ từ bi và sự chấp nhận vô điều kiện, khiến mọi người cảm thấy được chữa lành khi ở gần bạn.',
	},
	birthdayDescriptions: {
		1: 'Ngày sinh 1 mang năng lượng lãnh đạo. Bạn có tinh thần độc lập, sáng tạo và thích khởi xướng. Bạn là người tiên phong và có khả năng dẫn dắt người khác.',
		2: 'Ngày sinh 2 mang năng lượng hợp tác. Bạn có khả năng làm việc nhóm xuất sắc, nhạy cảm với cảm xúc người khác và thích hòa giải.',
		3: 'Ngày sinh 3 mang năng lượng sáng tạo. Bạn có tài năng nghệ thuật, giao tiếp tốt và luôn tràn đầy năng lượng tích cực.',
		4: 'Ngày sinh 4 mang năng lượng ổn định. Bạn thực tế, chăm chỉ, có tính kỷ luật cao và thích xây dựng nền tảng vững chắc.',
		5: 'Ngày sinh 5 mang năng lượng tự do. Bạn thích khám phá, phiêu lưu, thay đổi và không muốn bị ràng buộc.',
		6: 'Ngày sinh 6 mang năng lượng chăm sóc. Bạn có bản năng bảo vệ, yêu thương gia đình và quan tâm đến cộng đồng.',
		7: 'Ngày sinh 7 mang năng lượng tâm linh. Bạn thích tìm hiểu, nghiên cứu và khám phá những bí ẩn của cuộc sống.',
		8: 'Ngày sinh 8 mang năng lượng thành công. Bạn có tham vọng lớn, khả năng quản lý tốt và hướng tới thành tựu vật chất.',
		9: 'Ngày sinh 9 mang năng lượng nhân đạo. Bạn có tầm nhìn rộng, lòng từ bi và muốn cống hiến cho xã hội.',
		10: 'Ngày sinh 10 mang năng lượng lãnh đạo sáng tạo. Bạn kết hợp sự độc lập với khả năng sáng tạo độc đáo.',
		11: 'Ngày sinh 11 mang năng lượng trực giác mạnh. Bạn có khả năng truyền cảm hứng và kết nối với điều thiêng liêng.',
		12: 'Ngày sinh 12 mang năng lượng sáng tạo hợp tác. Bạn có thể kết hợp tài năng cá nhân với khả năng làm việc nhóm.',
		13: 'Ngày sinh 13 mang năng lượng sáng tạo thực tế. Bạn có khả năng biến ý tưởng thành hiện thực thông qua công việc chăm chỉ.',
		14: 'Ngày sinh 14 mang năng lượng tự do có kỷ luật. Bạn cần sự đa dạng nhưng vẫn có thể tổ chức và quản lý tốt.',
		15: 'Ngày sinh 15 mang năng lượng chăm sóc linh hoạt. Bạn quan tâm đến gia đình nhưng cũng cần không gian cá nhân.',
		16: 'Ngày sinh 16 mang năng lượng tâm linh trực giác. Bạn có khả năng nhìn thấu bản chất và tìm hiểu ý nghĩa sâu xa.',
		17: 'Ngày sinh 17 mang năng lượng thành công tâm linh. Bạn có thể đạt được thành tựu vật chất mà vẫn giữ được giá trị tinh thần.',
		18: 'Ngày sinh 18 mang năng lượng nhân đạo thực tế. Bạn muốn giúp đỡ người khác thông qua các hành động cụ thể.',
		19: 'Ngày sinh 19 mang năng lượng lãnh đạo độc lập. Bạn có khả năng dẫn dắt mà vẫn giữ được cá tính riêng.',
		20: 'Ngày sinh 20 mang năng lượng hợp tác nhạy cảm. Bạn có khả năng cảm nhận và hòa hợp với năng lượng xung quanh.',
		21: 'Ngày sinh 21 mang năng lượng sáng tạo hợp tác. Bạn có thể tạo ra những điều đẹp đẽ khi làm việc với người khác.',
		22: 'Ngày sinh 22 mang năng lượng Master Builder. Bạn có khả năng tạo ra những thành tựu lớn lao có tầm ảnh hưởng rộng rãi.',
		23: 'Ngày sinh 23 mang năng lượng giao tiếp linh hoạt. Bạn có khả năng truyền đạt ý tưởng một cách sinh động và thuyết phục.',
		24: 'Ngày sinh 24 mang năng lượng xây dựng gia đình. Bạn có khả năng tạo ra môi trường ấm áp và ổn định cho những người thân yêu.',
		25: 'Ngày sinh 25 mang năng lượng tìm tòi trực giác. Bạn có khả năng khám phá và hiểu biết thông qua trực giác mạnh mẽ.',
		26: 'Ngày sinh 26 mang năng lượng kinh doanh nhân văn. Bạn có thể thành công trong kinh doanh mà vẫn quan tâm đến con người.',
		27: 'Ngày sinh 27 mang năng lượng giáo dục nhân đạo. Bạn có khả năng dạy dỗ và hướng dẫn người khác một cách từ bi.',
		28: 'Ngày sinh 28 mang năng lượng lãnh đạo cân bằng. Bạn có thể lãnh đạo hiệu quả mà vẫn quan tâm đến nhu cầu của mọi người.',
		29: 'Ngày sinh 29 mang năng lượng trực giác nhân đạo. Bạn có khả năng cảm nhận và giúp đỡ người khác thông qua trực giác sâu sắc.',
		30: 'Ngày sinh 30 mang năng lượng sáng tạo vui vẻ. Bạn có khả năng mang lại niềm vui và sự sáng tạo cho cuộc sống.',
		31: 'Ngày sinh 31 mang năng lượng sáng tạo thực tế. Bạn có khả năng biến những ý tưởng sáng tạo thành hiện thực.',
	},
	attitudeDescriptions: {
		1: 'Thái độ số 1: Bạn tiếp cận cuộc sống với tinh thần lãnh đạo và độc lập. Bạn thích làm chủ tình hình và không ngại đối mặt với thử thách.',
		2: 'Thái độ số 2: Bạn tiếp cận cuộc sống với tinh thần hợp tác và nhạy cảm. Bạn thích làm việc cùng người khác và tạo ra sự hòa hợp.',
		3: 'Thái độ số 3: Bạn tiếp cận cuộc sống với tinh thần sáng tạo và lạc quan. Bạn luôn tìm cách làm cho mọi thứ trở nên thú vị và sinh động.',
		4: 'Thái độ số 4: Bạn tiếp cận cuộc sống với tinh thần thực tế và có tổ chức. Bạn thích lập kế hoạch chi tiết và làm việc một cách có hệ thống.',
		5: 'Thái độ số 5: Bạn tiếp cận cuộc sống với tinh thần tự do và phiêu lưu. Bạn thích khám phá những điều mới mẻ và không muốn bị ràng buộc.',
		6: 'Thái độ số 6: Bạn tiếp cận cuộc sống với tinh thần chăm sóc và trách nhiệm. Bạn luôn quan tâm đến gia đình và cộng đồng xung quanh.',
		7: 'Thái độ số 7: Bạn tiếp cận cuộc sống với tinh thần tìm tòi và tâm linh. Bạn thích suy ngẫm sâu sắc về ý nghĩa của mọi sự việc.',
		8: 'Thái độ số 8: Bạn tiếp cận cuộc sống với tinh thần thành công và quyết đoán. Bạn hướng tới các mục tiêu lớn và không ngại chấp nhận rủi ro.',
		9: 'Thái độ số 9: Bạn tiếp cận cuộc sống với tinh thần nhân đạo và bao dung. Bạn quan tâm đến lợi ích chung và muốn cống hiến cho xã hội.',
	},
	maturityDescriptions: {
		1: 'Số Trưởng Thành 1: Trong nửa đời sau, bạn sẽ phát triển khả năng lãnh đạo mạnh mẽ hơn. Bạn trở nên độc lập, tự tin và có khả năng khởi xướng những dự án mới. Đây là thời kỳ bạn thực sự trở thành người tiên phong.',
		2: 'Số Trưởng Thành 2: Trong nửa đời sau, bạn sẽ phát triển khả năng hợp tác và cân bằng. Bạn trở nên nhạy cảm hơn với nhu cầu của người khác và có khả năng xây dựng những mối quan hệ sâu sắc, ý nghĩa.',
		3: 'Số Trưởng Thành 3: Trong nửa đời sau, bạn sẽ phát triển khả năng sáng tạo và giao tiếp. Bạn có thể trở thành người truyền cảm hứng, nghệ sĩ hoặc diễn giả tài ba, mang lại niềm vui cho nhiều người.',
		4: 'Số Trưởng Thành 4: Trong nửa đời sau, bạn sẽ phát triển khả năng xây dựng và tổ chức. Bạn trở thành người đáng tin cậy, có thể tạo ra những nền tảng vững chắc cho bản thân và người khác.',
		5: 'Số Trưởng Thành 5: Trong nửa đời sau, bạn sẽ phát triển khả năng thích ứng và khám phá. Bạn có thể trở thành người du lịch, nhà thám hiểm hoặc người đem lại những thay đổi tích cực cho xã hội.',
		6: 'Số Trưởng Thành 6: Trong nửa đời sau, bạn sẽ phát triển khả năng chăm sóc và nuôi dưỡng. Bạn trở thành người cố vấn, thầy giáo hoặc người chăm sóc, mang lại sự ấm áp cho cộng đồng.',
		7: 'Số Trưởng Thành 7: Trong nửa đời sau, bạn sẽ phát triển khả năng tâm linh và trí tuệ. Bạn có thể trở thành nhà nghiên cứu, triết gia hoặc người dẫn dắt tâm linh, tìm kiếm những sự thật sâu xa.',
		8: 'Số Trưởng Thành 8: Trong nửa đời sau, bạn sẽ phát triển khả năng quản lý và kinh doanh. Bạn có thể đạt được thành công lớn về mặt vật chất và trở thành người có ảnh hưởng trong xã hội.',
		9: 'Số Trưởng Thành 9: Trong nửa đời sau, bạn sẽ phát triển khả năng phục vụ nhân loại. Bạn trở thành người có tầm nhìn toàn cầu, có thể cống hiến cho những mục tiêu cao cả và tạo ra tác động tích cực rộng lớn.',
		11: 'Số Trưởng Thành 11: Trong nửa đời sau, bạn sẽ phát triển khả năng truyền cảm hứng tâm linh. Bạn trở thành người thầy, người chữa lành hoặc người đem ánh sáng tâm linh đến cho nhiều người.',
		22: 'Số Trưởng Thành 22: Trong nửa đời sau, bạn sẽ phát triển khả năng xây dựng những dự án vĩ đại. Bạn có thể tạo ra những thay đổi có tầm ảnh hưởng quốc tế và để lại di sản lớn lao cho thế giới.',
		33: 'Số Trưởng Thành 33: Trong nửa đời sau, bạn sẽ phát triển khả năng yêu thương và chữa lành vô điều kiện. Bạn trở thành người thầy của tình yêu, có thể chữa lành tâm hồn của nhiều người thông qua lòng từ bi.',
	},
};

export { descriptions, baseVowels, letterValues, vietnameseAccents };
